export const QUERY_KEY = {
  // Auth
  ME: 'ME',
  // Products
  PRODUCT_LIST: 'PRODUCT_LIST',
  PRODUCT_BY_SKU: 'PRODUCT_BY_SKU',
  PRODUCT_DETAILS: 'PRODUCT_DETAILS',
  // Categories
  CATEGORY_LIST: 'CATEGORY_LIST',
  CATEGORY_DETAILS: 'CATEGORY_DETAILS',
  // Manufacturers
  MANUFACTURER_LIST: 'MANUFACTURER_LIST',
  MANUFACTURER_DETAILS: 'MANUFACTURER_DETAILS',
  // Tags
  TAG_LIST: 'TAG_LIST',
  TAG_DETAILS: 'TAG_DETAILS',
  // Brands
  BRAND_LIST: 'BRAND_LIST',
  BRAND_DETAILS: 'BRAND_DETAILS',
  // Orders
  ORDER_LIST: 'ORDER_LIST',
  ORDER_DETAILS: 'ORDER_DETAILS',
  // Dashboard
  DASHBOARD_OVERVIEW: 'DASHBOARD_OVERVIEW',
  // Customers
  CUSTOMER_LIST: 'CUSTOMER_LIST',
  // Create Transfer
  CREATE_TRANSFER_LIST: 'CREATE_TRANSFER_LIST',
  // Recipients
  RECIPIENT_LIST: 'RECIPIENT_LIST',
  // Transactions
  TRANSACTION_LIST: 'TRANSACTION_LIST',
  TRANSACTION_DETAILS: 'TRANSACTION_DETAILS',
  // Commissions
  COMMISSION_LIST: 'COMMISSION_LIST',
  // Profile
  PROFILE_DETAILS: 'PROFILE_DETAILS',
};
